# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40aa2dbdb977025e72df3b84753dae09f427ee9ee35922701fe18cf2fee35a17244ea4567735f6ec644be057e6078399144b0abf4317650315756c628b8717b6

test:
  secret_key_base: 13a84d8f890218847512448c8c5e864fc6c5b1fd654a0c1151d1a13d3d72d9997ab43e4728bb4de2c0e9ca1545f180d21e805058aec3c0f55d760884b5a866c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
